# VAE Training Configuration for TEMPO Spectral Data

# Output directory for all results
output_dir: data/vae_training/default_run

# Random seed for reproducibility
seed: 42

# Data configuration
data:
  # Training data directory (required)
  train_dir: data/tempo_jan2025_LA_tiles/train

  # Validation data directory (optional)
  val_dir: data/tempo_jan2025_LA_tiles/val

  # Batch size
  batch_size: 32

  # Number of data loading workers
  num_workers: 2  # Reduced to prevent OOM
  val_num_workers: 1

  # Minimum buffer size for random sampling
  min_buffer_size: 500
  val_min_buffer_size: 100

# Model configuration
model:
  # Input shape: [channels, height, width]
  shape: [1028, 64, 64]

  # Latent embedding dimension
  embed_dim: 32

  # Channel progression for encoder/decoder
  chs: [512, 256, 128]

  # Sizes at which to apply attention (empty = no attention except middle)
  attn_sizes: []

  # Use attention in middle block
  mid_attn: true

  # Number of residual blocks per level
  num_res_blocks: 1

  # Dropout probability
  dropout_prob: 0.0

  # Latent channels
  z_channels: 32

  # Double latent channels for mean and variance
  double_z: true

  # Number of attention heads
  n_attention_heads: 4

  # Group normalization settings
  norm_groups: 8
  norm_eps: 1.0e-6
  norm_affine: true

  # Activation function (gelu, relu, or silu)
  act: gelu

  # Convolution settings
  conv_kernel_size: 3
  conv_padding_mode: zeros

  # Loss weights
  kl_weight: 0.000001

  # Reconstruction loss type (l1 or l2)
  nll_loss_type: l1

# Optimizer configuration
optimizer:
  # Learning rate
  lr: 0.0001

  # Adam betas
  betas: [0.9, 0.95]

  # Weight decay
  weight_decay: 0.05

# Training configuration
training:
  # Total number of training steps
  n_steps: 200000

  # Save checkpoint every N steps
  save_every: 5000

  # Validate every N steps
  val_every: 50

  # Log metrics every N steps
  log_every: 10

  # Optional: Resume from checkpoint
  # resume_from: data/vae_training/previous_run/checkpoints/ckpt_step=050000.pt